name: Load EMS Data to AGO

on:
  schedule:
    - cron: 0 8 * * 0 # every Sunday at midnight PST
  workflow_dispatch:

jobs:
  run-scripts: 
    if: github.repository == 'bcgov/hullcar-watershed-app' # ensures the original workflow is run and not the forks
    runs-on: ubuntu-latest
    env:
        CKAN_API_URL: ${{  secrets.CKAN_API_URL  }}
        URL: ${{  secrets.MAPHUB_URL  }}
        USERNAME: ${{  secrets.GSS_ES_AGO_USERNAME  }}
        PASSWORD: ${{  secrets.GSS_ES_AGO_PASSWORD  }}
        HULLCAR_ITEM_ID: ${{  secrets.HULLCAR_ITEM_ID  }}
        HULLCAR_GROUP_ID: ${{  secrets.HULLCAR_GROUP_ID  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install libkrb5 for Kerberos on Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y krb5-user libkrb5-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script
        run: |
          python3 scripts/upload_ems_data_to_ago.py

    


